version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - pip install mkdocs-material==9.5.21
      - pip install mkdocstrings==0.25.0
      - pip install mkdocstrings-python==1.10.0
      - pip install mkdocs-macros-plugin==1.0.5
      - pip install jinja2==3.1.3

    # post_install:
    #   - poetry install --only doc